import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Mic, FileCode2, Shuffle, AlignCenter, Lock, Radio, ArrowRight } from 'lucide-react';
import { InfoCallout } from '../../components/interactive/ParameterPanel';

const STAGES = [
  {
    id: 'speech',
    icon: Mic,
    title: 'Speech Coding',
    rate: '13 kbps',
    color: '#ef4444',
    desc: 'Analog voice is sampled at 8 kHz (13-bit PCM) producing 104 kbps. The RPE-LTP speech coder compresses this down to 13 kbps by modeling the vocal tract.',
    action: 'Compresses Audio'
  },
  {
    id: 'channel',
    icon: FileCode2,
    title: 'Channel Coding',
    rate: '22.8 kbps',
    color: '#f59e0b',
    desc: 'Adds redundancy to protect against errors. The 260 bits of speech (per 20ms) are divided into classes. The most important bits get heavy convolutional coding, expanding the 260 bits to 456 bits.',
    action: 'Adds Parity/FEC'
  },
  {
    id: 'interleave',
    icon: Shuffle,
    title: 'Interleaving',
    rate: '22.8 kbps',
    color: '#10b981',
    desc: 'The 456 bits are scrambled and spread across 8 different time slots. If a deep fade destroys an entire burst, the errors are spread out when de-interleaved, allowing the Channel Decoder to correct them!',
    action: 'Scrambles Bits'
  },
  {
    id: 'burst',
    icon: AlignCenter,
    title: 'Burst Formatting',
    rate: '270.8 kbps (Burst Rate)',
    color: '#06b6d4',
    desc: 'The interleaved bits are packaged into a Normal Burst. Training sequences (for equalization), tail bits, and guard periods are added to fit the 577 μs time slot.',
    action: 'Adds Overhead'
  },
  {
    id: 'cipher',
    icon: Lock,
    title: 'Ciphering',
    rate: '270.8 kbps',
    color: '#8b5cf6',
    desc: 'The data bits are XORed with a pseudo-random bitstream generated by the A5/1 algorithm (using the Hyperframe Number and a secret key) to ensure privacy over the air.',
    action: 'Encrypts Data'
  },
  {
    id: 'modulate',
    icon: Radio,
    title: 'Modulation',
    rate: 'Analog RF Waveform',
    color: '#ec4899',
    desc: 'The digital bits are modulated onto a 900 MHz or 1800 MHz carrier using GMSK (Gaussian Minimum Shift Keying), which provides a constant envelope and narrow bandwidth.',
    action: 'GMSK to RF'
  }
];

export default function GSMSignalProcessing() {
  const [activeStage, setActiveStage] = useState(0);

  return (
    <div className="section-container py-10">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
        <div className="flex items-center gap-2 mb-2">
          <div className="w-2 h-2 rounded-full" style={{ background: '#3b82f6' }} />
          <span className="text-sm font-medium" style={{ color: '#3b82f6' }}>9.2 · GSM System</span>
        </div>
        <h1 className="mb-3">Signal Processing Chain</h1>
        <p className="text-lg mb-8 max-w-2xl" style={{ color: 'var(--color-text-secondary)' }}>
          Follow the journey of a human voice as it is digitized, compressed, protected, scrambled, encrypted, and finally transmitted over the airwaves in a GSM network.
        </p>

        <div className="grid lg:grid-cols-12 gap-6 mb-8">
          {/* Pipeline */}
          <div className="lg:col-span-5 flex flex-col gap-2">
            {STAGES.map((stage, idx) => {
              const Icon = stage.icon;
              const isActive = activeStage === idx;
              const isPast = idx < activeStage;
              
              return (
                <div key={stage.id} className="relative">
                  {/* Connecting Line */}
                  {idx < STAGES.length - 1 && (
                    <div className="absolute left-[23px] top-12 w-[2px] h-4 bg-white/10 z-0" />
                  )}
                  
                  <button onClick={() => setActiveStage(idx)}
                    className={`relative z-10 w-full flex items-center gap-4 p-3 rounded-xl transition-all border text-left
                      ${isActive ? 'bg-white/10 border-white/30 shadow-lg scale-105' : 
                        isPast ? 'bg-black/20 border-white/5 opacity-70 hover:opacity-100' : 'bg-transparent border-transparent hover:bg-white/5 opacity-50 hover:opacity-100'}`}
                  >
                    <div className="w-12 h-12 rounded-lg flex items-center justify-center flex-shrink-0"
                         style={{ background: isActive ? stage.color : 'var(--color-bg-tertiary)' }}>
                      <Icon size={20} color={isActive ? 'white' : 'var(--color-text-tertiary)'} />
                    </div>
                    <div className="flex-1">
                      <div className="font-bold text-sm" style={{ color: isActive ? 'white' : 'var(--color-text-secondary)' }}>
                        {idx + 1}. {stage.title}
                      </div>
                      <div className="text-xs font-mono mt-0.5" style={{ color: isActive ? stage.color : 'var(--color-text-tertiary)' }}>
                        {stage.action}
                      </div>
                    </div>
                    {isActive && <ArrowRight size={18} color={stage.color} />}
                  </button>
                </div>
              );
            })}
          </div>

          {/* Details Panel */}
          <div className="lg:col-span-7">
            <AnimatePresence mode="wait">
              <motion.div 
                key={activeStage}
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.2 }}
                className="glass-card p-8 h-full flex flex-col justify-center border-t-4"
                style={{ borderTopColor: STAGES[activeStage].color }}
              >
                <div className="w-16 h-16 rounded-2xl flex items-center justify-center mb-6"
                     style={{ background: `color-mix(in oklch, ${STAGES[activeStage].color} 15%, transparent)` }}>
                  {(() => {
                    const ActiveIcon = STAGES[activeStage].icon;
                    return <ActiveIcon size={32} color={STAGES[activeStage].color} />;
                  })()}
                </div>
                
                <h2 className="text-2xl font-bold mb-2">{STAGES[activeStage].title}</h2>
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-mono font-bold w-max mb-6"
                     style={{ background: 'var(--color-bg-tertiary)', color: STAGES[activeStage].color }}>
                  Output Rate: {STAGES[activeStage].rate}
                </div>
                
                <p className="text-base leading-relaxed" style={{ color: 'var(--color-text-secondary)' }}>
                  {STAGES[activeStage].desc}
                </p>

                {activeStage === 2 && (
                  <div className="mt-6 p-4 bg-black/30 rounded-lg text-sm border border-emerald-500/20">
                    <strong className="text-emerald-400">Why Interleave?</strong> Fading causes errors to happen in bursts (e.g., wiping out 50 bits in a row). Error correction codes fail if too many consecutive bits are lost. Interleaving scatters the bits over 40ms, so a burst error becomes isolated, random errors that the decoder can easily fix!
                  </div>
                )}
                
                {activeStage === 4 && (
                  <div className="mt-6 p-4 bg-black/30 rounded-lg text-sm border border-violet-500/20">
                    <strong className="text-violet-400">Security Note:</strong> A5/1 was designed in the 1980s. Due to export restrictions, its effective key length was deliberately weakened. Today, A5/1 can be cracked in real-time using rainbow tables, which is why 2G networks are considered highly insecure.
                  </div>
                )}
              </motion.div>
            </AnimatePresence>
          </div>
        </div>

        <InfoCallout type="guide" title="How to use this visualizer">
          <strong>Goal:</strong> Follow the lifecycle of a digital bit in a 2G network.<br/>
          <strong>Action:</strong> Click through steps 1 to 6 sequentially.<br/>
          <strong>Practical Conclusion:</strong> Notice how the data rate changes at each step. We start with 104 kbps of raw audio, compress it heavily to 13 kbps to save bandwidth, and then immediately bloat it back up to 22.8 kbps with error-correction overhead! This teaches a fundamental engineering lesson: you must aggressively compress the source data so you have "budget" left over to add redundancy for the harsh wireless channel.
        </InfoCallout>
      </motion.div>
    </div>
  );
}
